(require 'go-mode-autoloads)
(require 'bind-key)
(setq exec-path (cons "/usr/local/bin/" exec-path))
(defun my-go-mode-hook ()
  (add-hook 'before-save-hook 'gofmt-before-save)
  (if (not (string-match "go" compile-command))
      (set (make-local-variable 'compile-command)
           "go generate && go build -v"))
  (require 'go-flymake)
  (require 'go-flycheck)
  ;; (require 'go-errcheck)
  ;; (setq go-errcheck-ignore "io:Write,io:Read")
  (auto-complete-mode 1)
  ;; (speedbar-add-supported-extension ".go")
  (setq imenu-generic-expression
          '(("type" "^type *\\([^ \t\n\r\f]*\\)" 1)
            ("func" "^func \\(.*\\)\s*\\(([^)]*)\\).*{" 1)))
            ;; ("func" "^func .*\\([^ \{]*[\(not )]*.*\\) {" 1)))
  (imenu-add-to-menubar "Index")
  (global-unset-key (kbd "M-]"))
  (global-set-key (kbd "M-]") 'godef-jump))
(add-hook 'go-mode-hook 'my-go-mode-hook)
(add-hook 'go-mode-hook 'go-eldoc-setup)
(require 'go-autocomplete)
(ac-config-default)
(provide 'init-gomode)