;;; -*- mode: lisp; coding: utf-8-unix -*-
(require 'go-mode-autoloads)
(setq exec-path (cons "/usr/local/bin/" exec-path))
(defun my-go-mode-hook ()
  (add-hook 'before-save-hook 'gofmt-before-save)
  (if (not (string-match "go" compile-command))
      (set (make-local-variable 'compile-command)
           "go generate && go build -v"))
  ;; (require 'go-errcheck)
  ;; (setq go-errcheck-ignore "io:Write,io:Read")
  (auto-complete-mode 1)
  ;; (speedbar-add-supported-extension ".go")
  (setq imenu-generic-expression
        '(("type" "^type *\\([^ \t\n\r\f]*\\)" 1)
          ("func" "^func \\(.*\\)\s*\\(([^)]*)\\).*{" 1)))
  ;; ("func" "^func .*\\([^ \{]*[\(not )]*.*\\) {" 1)))
  (imenu-add-to-menubar "Index")
  (flyspell-mode-off)
  (setq dash-at-point-docset "go")
  (local-unset-key (kbd "M-]"))
  (local-set-key "\M-." 'godef-jump))

(require 'go-flymake)
(require 'go-flycheck)
(add-hook 'go-mode-hook 'my-go-mode-hook)
(require 'go-eldoc)
(set-face-attribute 'eldoc-highlight-function-argument nil
                    :underline t :foreground "green"
                    :weight 'bold)
(add-hook 'go-mode-hook 'go-eldoc-setup)
(require 'go-autocomplete)
(ac-config-default)
(provide 'init-gomode)